---
admin_user: ubuntu

docker_app_dir: /opt/docker-secure-platform

base_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apt-transport-https
  - software-properties-common
  - git
  - unzip
  - htop
  - vim
  - jq

docker_users:
  - ubuntu

ssh_port: 22
admin_public_ip_cidr: "88.178.119.146/32"

security_packages:
  - ufw
  - fail2ban
