---
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "${NPM_HTTP_PORT}:80"
      - "${NPM_HTTPS_PORT}:443"
    environment:
      TZ: "${TZ}"
    volumes:
      - "${NPM_DATA_PATH}:/data"
      - "${NPM_LETSENCRYPT_PATH}:/etc/letsencrypt"
    networks:
      - proxy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${PORTAINER_DATA_PATH}:/data"
    networks:
      - proxy

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    volumes:
      - "${UPTIME_KUMA_DATA_PATH}:/app/data"
    networks:
      - proxy

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      HOMEPAGE_ALLOWED_HOSTS: "frikzai-home.duckdns.org"
    volumes:
      - "${HOMEPAGE_CONFIG_PATH}:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
